name: Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: ''
          - platform: ubuntu-22.04
            args: --bundles deb,rpm
          - platform: windows-latest
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - run: git config --global url."https://x-access-token:${{ secrets.CORE_REPO_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - run: npm ci

      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseDraft: true
          prerelease: false
          uploadWorkflowArtifacts: true
          args: ${{ matrix.args }}
