name: Release (Windows self-hosted)

on:
  workflow_dispatch:
  push:
    branches: [feat/setup-github-actions]
    paths: ['.github/workflows/release-windows-local.yml']

permissions:
  contents: write

jobs:
  publish-tauri:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4

      - run: git config --global url."https://x-access-token:${{ secrets.CORE_REPO_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - run: npm ci

      - uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseDraft: true
          prerelease: false
          uploadWorkflowArtifacts: true
